apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-dev
  template:
    metadata:
      labels:
        app: my-app-dev
    spec:
      containers:
      - name: test-container
        image: aranaivo/myphpapp
        command: ["/bin/sh", "-c", "echo ENV NAME: $(ENVNAME) LOGIN: $(APPLOGIN) PASSWORD: $(APPPWD)"]
        ports:
        - containerPort: 80
        env:
        - name: ENVNAME
          valueFrom:
            configMapKeyRef:
              name: dev-env
              key: envname
        - name: APPLOGIN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: APPPWD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
