apiVersion: v1
kind: Pod
metadata:
  name: test_configmap
spec:
  containers:
    - name: test-container
      image: aranaivo/myphpapp
      command: ["/bin/sh", "-c", "echo ENV NAME: $(ENVNAME)"]
      env:
        - name: ENVNAME
          valueFrom:
            configMapKeyRef:
              name: dev-env
              key: envname
  restartPolicy: Never
