apiVersion: v1
kind: Service
metadata:
  name: myapp-dev
  namespace: dev
  labels:
    app: my-app-dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: my-app-dev
